module.exports.partner = require('./routes/partner.route')
module.exports.user = require('./routes/user.route')
module.exports.certificate = require('./routes/certificate.route')
module.exports.expertise = require('./routes/expertise.route')
module.exports.baseCertificate = require('./routes/baseCertificate.route')